### ISSUE TITLE
Uncomplete dependencies in Ubuntu

### ISSUE THREAD

**Issue by muhlpachr** [bigclownlabs/bc-doc#20]
At least build-essential dependency is missing in build instructions, build should be tested on clean Ubuntu.

**Comment by bc-pavel-hubner** [comment]
Resolved.

**Comment by jirutka** [comment]
@bc-pavel-hubner Please do not close issues until the fix is merged into the master branch. Moreover it’d be closed automatically, because I’ve mentioned this issue in the commit message. ;)

**Comment by bc-pavel-hubner** [comment]
Okay, I will do better next time ;-)
