### ISSUE TITLE
The dashboard keeps saying "Disconnected"

### ISSUE THREAD

**Issue by Inza** [bigclownlabs/bc-doc#6]
Hello Guys,

The alpha set is just amazing, I just have one little problem with my setup.

I have setup everything based on your great tutorial (https://www.bigclown.com/alpha), and it seems to work, but I am unable to see anything on my dashboard. It keeps saying "Disconnected".

* I have a raspi2
* I am able to see the log from the HW via the MQTT inspect (docker exec hub mosquitto_sub -v -t 'nodes/bridge/0/#')
* I am able to control the servo via MQTT command examples you provided
* I have managed to setup the caddy server as well (I see the dashboard page, I will perform the HTTP basic auth, but then no data just a message Disconected)

How can I fix this? Do I need to provide custom source in Settings of the dashboard?

Thanks! ;)

**Comment by Inza** [comment]
It does not matter if I use the hub.local, or raspi IP, the issue remains...

**Comment by Inza** [comment]
I can see this in the caddy error log:

```
$ cat /var/hub/log/caddy-errors.log
06/Nov/2016:17:45:35 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:17:51:53 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:17:57:50 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:17:58:05 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_simulator] websocket: response does not implement http.Hijacker
06/Nov/2016:17:58:13 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:18:00:31 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:18:00:35 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:18:00:55 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: version != 13
06/Nov/2016:18:02:53 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: version != 13
06/Nov/2016:18:06:02 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:18:06:42 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
06/Nov/2016:18:13:02 +0000 [ERROR 400 /auth/clown-talk-server_nodes_bridge_0] websocket: response does not implement http.Hijacker
```

**Comment by Inza** [comment]
And this in the caddy access log:

```
192.168.1.49 - [06/Nov/2016:18:12:46 +0000] "GET /app HTTP/2.0" 301 50
192.168.1.49 - [06/Nov/2016:18:12:46 +0000] "GET /auth/dashboard HTTP/2.0" 401 17
192.168.1.49 - [06/Nov/2016:18:12:59 +0000] "GET /auth/dashboard HTTP/2.0" 307 52
192.168.1.49 - [06/Nov/2016:18:12:59 +0000] "GET /auth/dashboard/ HTTP/2.0" 200 13596
192.168.1.49 - [06/Nov/2016:18:12:59 +0000] "GET /auth/dashboard/config.js HTTP/2.0" 200 728
192.168.1.49 - [06/Nov/2016:18:13:00 +0000] "GET /auth/dashboard/bundle.js HTTP/2.0" 200 200946
192.168.1.49 - [06/Nov/2016:18:13:02 +0000] "GET /auth/clown-talk-server_nodes_bridge_0 HTTP/1.1" 401 17
192.168.1.49 - [06/Nov/2016:18:13:02 +0000] "GET /auth/clown-talk-server_nodes_bridge_0 HTTP/1.1" 400 38
192.168.1.49 - [06/Nov/2016:18:13:02 +0000] "GET /favicon.ico HTTP/2.0" 404 14
```

**Comment by jirutka** [comment]
Hi,

since you have RPi 2, you’ve followed [instructions to replace Caddy](https://github.com/bigclownlabs/bc-doc/blob/master/doc/raspberry-pi.md#notes-for-raspberry-pi-2), right?

The problem is that the last “stable” version of Caddy (0.9.3) has broken WebSockets. We have tested version 0.9.1, I’m not sure about 0.9.2. So please replace your caddy binary with version 0.9.1 from https://github.com/mholt/caddy/releases/download/v0.9.1/caddy_linux_arm7.tar.gz (or compile it from [source](https://github.com/mholt/caddy/archive/v0.9.1.tar.gz)).

Sorry for complications, we will replace Caddy with a reliable web server in next release. Meanwhile I’m gonna update the documentation.

**Comment by Inza** [comment]
Epic :-( Can I download this version of Caddy in a binary form from somewhere? And install it in a same (or similar) simple way how I did the lates version?

Thanks ;)

And BTW nice to see you Jakub :-D world is so small...

**Comment by Inza** [comment]
Is there any way how to install the 0.9.1 version from https://getcaddy.com ?

**Comment by jirutka** [comment]
The link I provided in my previous comment is for binary: https://github.com/mholt/caddy/releases/download/v0.9.1/caddy_linux_arm7.tar.gz. ;)

The exact steps are:

```sh
wget -O - https://github.com/mholt/caddy/releases/download/v0.9.1/caddy_linux_arm7.tar.gz | tar -xz caddy_linux_arm7
mv caddy_linux_arm7 /var/hub/caddy
```

Well, world is quite big, but Czech Republic is indeed very small. ;)

**Comment by Inza** [comment]
Hello,

I performed the described steps (I reinstalled the caddy server to the 0.9.1) and I moved it to the container (with `docker exec hub cp /var/hub/caddy /usr/local/bin/caddy`).

Do I need restart the server? I tried stop and start the container again, but now I cannot connect to the Dashboard site what so ever...

My docker ps says that the container is running:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                             NAMES
df039dc9ee31        clown/rpi-hub       "/usr/bin/hub supervi"   7 minutes ago       Up 7 minutes        80/tcp, 0.0.0.0:1883->1883/tcp, 443/tcp, 0.0.0.0:8080->8080/tcp   hub
```

I even tried to stop it, remove it, and run again with the command from docs:

```
docker run -d -p 8080:8080 -p 1883:1883 --privileged -v /dev:/dev \
  -v /var/hub:/var/hub -h hub-container --name hub clown/rpi-hub
```

Then I again `mv` the new caddy into it.

But still my Chrome says:

```
This site can’t be reached

192.168.1.213 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

![screen shot 2016-11-17 at 8 58 27](https://cloud.githubusercontent.com/assets/103046/20380715/0afcc162-aca4-11e6-8867-63f850fee8a5.png)

What am I doing wrong? It does not work either with the `https://hub.local:8080/dashboard` nor with IP address of my pi...

How can I find out that the caddy is running at all in my docker container? Do I need to restart it after putting it there?

Thanks

**Comment by Inza** [comment]
OK, so the issue is that the caddy is not running inside the container...

When I run `docker exec -it hub bash` and bash myself to the container and I try `ps -ef` I get:

```
PID   USER     TIME   COMMAND
    1 root       0:42 {supervisord} /usr/bin/python /usr/bin/supervisord -c /etc/supervisord.conf
   15 root       0:13 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
   16 root       1:03 {clown-talk-clie} /usr/bin/python3.5 /usr/bin/clown-talk-client mqtt://localhost nodes/bridge/0 bc-bridge
   17 root       0:14 {bridge-simulato} /usr/bin/python3.5 /usr/bin/bridge-simulator mqtt://localhost nodes/bridge/simulator
   43 root       0:31 bc-bridge
  577 root       0:03 mosquitto_sub -v -t nodes/bridge/0/#
 8331 root       0:00 bash
 8367 root       0:00 ps -ef
```

No sign of caddy running there... Where is the Caddyfile stored inside the container?

**Comment by Inza** [comment]
Probably the default `/etc/caddy.conf`, right?

You run the caddy via supervisord, right?

So maybe when I now restart the supervisor it should work?

I tried `/usr/bin/supervisord -c /etc/supervisord.conf` but that run the supervisord in some weird interactive mode and kept looping forewer trying to run the `blynk-client`...

```
2016-11-17 08:51:05,253 INFO spawned: 'blynk-client' with pid 10357
2016-11-17 08:51:06,252 INFO success: blynk-client entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-17 08:51:06,856 INFO exited: blynk-client (exit status 255; not expected)
2016-11-17 08:51:07,280 INFO spawned: 'blynk-client' with pid 10368
2016-11-17 08:51:08,284 INFO success: blynk-client entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-17 08:51:08,863 INFO exited: blynk-client (exit status 255; not expected)
```

I am starting to thing if is there is a real way how to get this thing working on a RPi2 at all... :-( ...

Have you actually get it running there? Or are you testing on RPi3 and only type some "command hints" how you think it may work on RPi2?

I would greatly appreciate a real step by step instructions for RPi2... a working one - not just a tutorial for RPi3 owners with a note like (BTW if you have RPi2, you just need to do this caddy install - and when you do, it will still not work...). I know it is an alpha set, but it may be nice that I will be able to see it running on order to start experimenting with it...

Or just say that you do not support RPi2 at all and I will get a RPi3...

Because this is not a support, it is more like a bad dream...

Thanks

**Comment by Inza** [comment]
I am not a pro for supervisord, caddy, etc. And I just hoped that I will be able to run the alpha kit on RPi2 without becoming one...

So let me know please if there is any way for me to run it on my RPi2 (and test it please that it works for you too).

Now I think that the only one thing which is letf is to run the downgraded caddy - or somehow convince that supervisord to restart - which I do not have a clue how to do so.

But it is weird that just rebooting the container or pi will not help...any idea why?

Thanks

**Comment by vlaxa** [comment]
My RPi2 setup is working well, Im able to provide functional caddy binary from my setup.

**Comment by Inza** [comment]
I tryied to restart just the caddy service using supervisord (I hope I am doing it the right way?):

```
root@hub-container:/# supervisorctl restart caddy
unix:///run/supervisord.sock refused connection
```

But as you can see it answered `unix:///run/supervisord.sock refused connection` - which does not look like OK message?

Unfortunately I do not know how to fix this...

**Comment by Inza** [comment]
@vlaxa OK, nice! :-), how you have convinced the `supervisord` to run the updated caddy binary? Or which steps have you took? Do you have any clue why my supervisord do not wants to boot up with the caddy? Or what is a proper way to reboot the supervised processes?

Thanks

**Comment by vlaxa** [comment]
You do not need any other reconfiguration after caddy binary exchange. You should simply restart docker container by docker stop hub | docker start hub

**Comment by Inza** [comment]
I did that but it does not work :-(

Why bash commands have you used? In order to download and run the docker image and update the caddy?

**Comment by Inza** [comment]
I just removed the docker container and docker image (and the /var/hub folder and created it again empty) and now the docker container crashes on start :-(.

Who should own the /var/hub folder? And who should be allowed to write into it?

In the code example in docs the folder is created as sudo, hence is owned by root.

But the copy caddy command is done by the default (pirate) user, so it looks like this:

```
ls -all /var/hub/
total 12960
drwxr-xr-x  2 root   root       4096 Nov 17 10:18 .
drwxr-xr-x 12 root   root       4096 Nov 17 10:17 ..
-rwxr-xr-x  1 pirate pirate 13261857 Aug 17 20:11 caddy
```

Is this OK? Or should somebody else be able to write there? Under which user the docker container runs? As root?

Any idea how can I find out why the docker container crashed? Any logs or something similar?

My `docker ps -all` says:

```
$ docker ps -all
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
076c2247c122        clown/rpi-hub       "/usr/bin/hub supervi"   2 minutes ago       Exited (2) 39 seconds ago                       hub
```

**Comment by vlaxa** [comment]
Initial RPi2 instructions at the BigClown github was  from my working setup.

```
$ ls -lha
total 13M
drwxr-xr-x  6 root root 4.0K Sep 27 14:58 .
drwxr-xr-x 12 root root 4.0K Sep 24 08:22 ..
-rwxr-xr-x  1 root root  13M Sep 27 14:58 caddy
drwxr-xr-x  2 root root 4.0K Nov 17 10:33 data
drwxr-xr-x  2 root root 4.0K Sep 28 18:35 log
drwxr-xr-x  3 root root 4.0K Sep 24 08:28 plugins
drwxr-xr-x  4 root root 4.0K Sep 27 15:00 www
```

caddy is owned by root

I will try to remove my docker image and build new one again.

**Comment by Inza** [comment]
What is the correct sequence of commands which I should enter in order to get the alpha set working on RPi2?

Lets assume I have just downloaded and installed the hypriot os image.

I have logged in via SSH and I have changed my password.

Then I have executed this:

```
sudo mkdir /var/hub
wget -O - https://github.com/mholt/caddy/releases/download/v0.9.1/caddy_linux_arm7.tar.gz \
  | tar -xz caddy_linux_arm7
mv caddy_linux_arm7 /var/hub/caddy
```

Now I would like to execute the `docker exec hub cp /var/hub/caddy /usr/local/bin/caddy` which I cannot, because I do not have any docker container yet - so this command will fail saying that the `hub` docker container does not exist - which is correct.

Do I pull and run the docker container with the provided command:

```
docker run -d -p 8080:8080 -p 1883:1883 --privileged -v /dev:/dev \
  -v /var/hub:/var/hub -h hub-container --name hub clown/rpi-hub
```

The container is pulled and started and it crashes (with exist status of 2).

When I try to run the `docker exec hub cp /var/hub/caddy /usr/local/bin/caddy` again it failed again, because the docker container is not running (because it crashed)...

So I tries a nasty trick thinking that the docker container keeps crashing because he misses the caddy binary - so I tried to do the copy in a pipe hoping that it will be copied fast enough that it will finish before the container crashes.

I did:

```
$ docker start hub && docker exec hub cp /var/hub/caddy /usr/local/bin/caddy
hub
```

Which looks like it succeeded, but the container crashed again...

And even when I try to restart it with `docker start hub` it keeps crashing.

What am I doing wrong? How to fix this?

@vlaxa you said that it works on your RPi2 which is nice, but can you please confirm how exactly you have reached that state? Have you followed the instructions provided in the docs? Or have you done anything in addition? Or differently?

Or can somebody test the instructions which are provided in your docs (and described above by me) and tell me that they worked for him? Or maybe correct me if I understand them wrongly?). I am just trying to figure out if I am doing something wrongly or if just the instructions suck, or where the heck is a problem...

It would be nice to have something like this in docs...

A) Instructions for RPi3 owners:

1) ...
2) ...

B) Instructions for RPi2 owners:

1) Do ...
2) Pull and run the docker image by running this command ...
3) ...

The goal is that when somebody will follow the instructions, he will not run into issues like this: where something (like docker exec ...) needs to be in fact run after something else (like docker run) - even that the docker exec is shown in your docs BEFORE the docker run - that is extremely confusing for users, especially those who are not docker gurus...

cc @jirutka  

Thanks

**Comment by Inza** [comment]
@vlaxa OK, so I will try to chmod caddy to root... lets see...

So I adjusted ownership of caddy to root by this: `chown root:root /var/hub/caddy`

So the result is this:

```
$ ls -all /var/hub/
total 12960
drwxr-xr-x  2 root root     4096 Nov 17 10:18 .
drwxr-xr-x 12 root root     4096 Nov 17 10:17 ..
-rwxr-xr-x  1 root root 13261857 Aug 17 20:11 caddy
```

But docker image keeps crashing...

**Comment by Inza** [comment]
I assume that the other directories except the caddy binary will be automatically created by the docker image, correct?

**Comment by vlaxa** [comment]
OK, RPi2 notes should by placed after docker image build because first of all you need running docker image and after that you can exchange caddy web server binary.

**Comment by vlaxa** [comment]
But, something is wrong! When I downloaded new container and try to run it, it is crashing too. I need o investigate it more in deep.

**Comment by Inza** [comment]
OK, so at least I am not the only one!

So I have crossed fingers for you and let me know when you will find our how to fix it.

Thanks

**Comment by bc-pavel-hubner** [comment]
Hi guys, our apology for running into these difficulties. We are working day & night to roll out the new Docker images which will fix a few things. By the way we are switching to nginx from Caddy so this will not be an issue anymore. When is this gonna happen? Well, most of the components are ready to be released so I expect it to be done by tomorrow, the latest. Thanks a lot ! Pavel

**Comment by Inza** [comment]
@bc-pavel-hubner Nice;) Thanks a lot;). Ngnix seems to be a far better (more stable option) looking forward!

**Comment by vlaxa** [comment]
If caddy web server did not work for you, you can try Blync integration https://github.com/bigclownlabs/bc-doc/blob/master/source/tutorial/blynk.adoc But if you will run it on the RPi2 you should use `clown/rpi-hub` docker image. This image is working for me right now.

**Comment by bc-pavel-hubner** [comment]
@Inza + @vlaxa: Good morning guys, our colleague @muhlpachr has released the new container last night - please see https://hub.docker.com/r/clown/rpi-hub/ for Raspberry Pi and https://hub.docker.com/r/clown/hub/ for x64. I have not tested it yet personally but this release is in fact huge leap in core technologies and implementation. Feedback and contributions are very welcome :-) Thanks!

**Comment by Inza** [comment]
Hello, I have remove my container and the old image and downloaded new image.

Still getting the "This site can’t provide a secure connection" error. Any idea how to solve it? Can it be caused by something bad in my hypriot image?

![screen shot 2016-11-21 at 22 50 05](https://cloud.githubusercontent.com/assets/103046/20502141/10c807fe-b03d-11e6-85ef-78af44f5e0c8.png)

**Comment by Inza** [comment]
The nginx access log shows this:

```
192.168.1.49 - - [21/Nov/2016:21:53:23 +0000] "\x16\x03\x01\x00\xB9\x01\x00\x00\xB5\x03\x035C\xF8\xC7\xF5\x89\x09\x22\xEB\xA6\x10\x8A\xA2\x96$\x0B\xE8\xF1;\xA2\xF0\x13\xF0\xA3\x82\xA3\xED\xD7\xC7\x9Au\xFA\x00\x00\x22\xCC\xA9\xCC\xA8\xCC\x14\xCC\x13\xC0+\xC0/\xC0,\xC00\xC0\x09\xC0\x13\xC0" 400 166 "-" "-" "-"
192.168.1.49 - - [21/Nov/2016:21:53:23 +0000] "\x16\x03\x01\x00\xB9\x01\x00\x00\xB5\x03\x03\x11M*\x9A\x03\xE3\x01Q\x1B\xCF\x16\x10\x03\xDC\x9C\x80\xD9\xEF\x04\x12\x93\x10\xCF\xCB9<\xE7\xAFb\x86\xDA\xC0\x00\x00\x22\xCC\xA9\xCC\xA8\xCC\x14\xCC\x13\xC0+\xC0/\xC0,\xC00\xC0\x09\xC0\x13\xC0" 400 166 "-" "-" "-"
```

**Comment by Inza** [comment]
And nginx error log is empty...

```
root@hub-container:/# ls -all /var/log/nginx/error.log 
-rw-r--r--    1 root     root             0 Nov 21 21:46 /var/log/nginx/error.log
```

**Comment by Inza** [comment]
Any ideas how to fix this? The docker container is running and everything inside appears to run as well...

```
root@hub-container:/# ps -ef
PID   USER     TIME   COMMAND
    1 root       0:14 {supervisord} /usr/bin/python /usr/bin/supervisord -c /etc/supervisord.conf
   11 root       0:02 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
   12 root       0:11 {clown-talk-clie} /usr/bin/python3.5 /usr/bin/clown-talk-client mqtt://localhost nodes/bridge/0 bc-bridge
   13 root       0:05 {bridge-simulato} /usr/bin/python3.5 /usr/bin/bridge-simulator mqtt://localhost nodes/bridge/simulator
   14 nobody     0:04 {clown-talk-ws-s} /usr/bin/python3.5 /usr/bin/clown-talk-ws-server --port=8090
   15 root       0:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf -g pid /run/nginx.pid; daemon off;
   17 nginx      0:00 nginx: worker process
   18 nginx      0:00 nginx: worker process
   28 root       0:05 bc-bridge
  622 root       0:00 bash
 1176 root       0:01 python3 /var/hub-container/plugins/blynk-vhw/blynk-client.py
 1193 root       0:00 ps -ef
```

**Comment by Inza** [comment]
@bc-pavel-hubner So I like a lot nginx instead of that crappy caddy, but my issue unfortunately still remains... :-( ... Any ideas what could be causing it? I have some experience with nginx and webservers but not much with https or SSL - can my issue be caused by that? On windows I get the same error, just in czech :-D.

It is the same regardless I use the IP of raspi or the hub.local ...

And I have RPi2

**Comment by jirutka** [comment]
It does not run over HTTPS anymore, the correct address is http://hub.local:8080/.

I wanted to provide link to the documentation, but now I see that we have it wrong here. Sorry for that, I’ll fix it immediately.

btw I’m glad that you like our decision to replace crappy caddy with nginx! 😺

**Comment by bc-pavel-hubner** [comment]
Thanks Jakub for clarifying this. Also it is worth noting why have we abandoned HTTPS. Well - because we had self-signed certificates and there were complaints about these from web-browsers. And from security perspective their real effect is questionable and most likely bad :-) So we are trimming the safe zone to Raspberry Pi only (locally) and considering other options. @muhlpachr has proposed SSH connection with TCP port tunneling which seems more viable to me. So then you will still be opening HTTP but  on localhost and over a secure tunnel. The same for Mosquitto. We are currently evaluating this option.

**Comment by Inza** [comment]
@jirutka @bc-pavel-hubner Thanks for reply guys, I will test this today evening. And ditch off that self-signed https makes sense as well. TCP via SSH tunnel seems a better way :-).

I will let you know if it is finally working for me. And hopefully we will be able to finally close this epic issue :-D.

**Comment by bc-pavel-hubner** [comment]
Thanks @Inza . We still need to update the documentation even more. For example in our lab we do not run HypriotOS on Raspberry Pi anymore. Instead we run Docker on clean install of Raspbian Jessie Lite. However sorting the way we do the documentation has higher priority now. Stay tunned and keep us posted :-)

**Comment by Inza** [comment]
@bc-pavel-hubner And just to be curious - why? Docker on clean Raspbian Jessie Lite performs better? or it is a more common setup?

**Comment by bc-pavel-hubner** [comment]
Exactly - let's assume that many geeks already have Raspberry Pi. Most of them are already running Raspbian on it. Why should we force them to reinstall the system just to run our container? :-) Moreover HypriotOS is also Raspbian with pre-installed Docker and some minor tweaks I do not really like by default - e.g. pirate alike shell and user ... LOL? Not really ;-) But it was a quick choice for us. Now it is the time to polish things a bit before we make a huge leap forward.

**Comment by Inza** [comment]
IT WORKS! Finally! So closing the issue.
